# Classification of NBA players role

Dataset description

The dataset of NBA basketball players data are gathered from (https://www.kaggle.com/jacobbaruch/nba-player-of-the-week).

The perceptron algorithm is implemented in this scenario.

In [1]:
!pip install numpy
!pip install scipy
!pip install matplotlib
!pip install sklearn


%matplotlib inline
import matplotlib.pyplot as plt
import csv

import numpy as np
import scipy as sp
import sklearn as sl
from scipy import stats
from sklearn import datasets
from sklearn import linear_model

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1320 sha256=e557e26b9aac882368c48355b942c6e18aac819f91304b0b58ea4877fbbf1d1e
  Stored in directory: c:\users\yukse\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn


In [2]:
#load the dataset
filename = 'data/NBA.csv' 
NBA = csv.reader(open(filename, newline=''), delimiter=',')

header = next(NBA) 
print(header)

dataset = list(NBA)
for i in range(len(dataset)):
    dataset[i] = [int(x) for x in dataset[i]]
    
dataset = np.asarray(dataset)

X = dataset[:,1:4] #columns 1,2,3 contain the features
Y = dataset[:,0]  # column 0: labels

Y = Y*2-1  

m = dataset.shape[0]
permutation = np.random.permutation(m) # random permurtation

X = X[permutation]
Y = Y[permutation]
print(X)
print(Y)
print(permutation)

['Position', 'Height cm', 'kg', 'Age']
[[182  78  29]
 [213 108  24]
 [186 108  22]
 [185  76  24]
 [213 119  23]
 [182  78  28]
 [188  87  24]
 [216 114  30]
 [210 114  24]
 [192  90  21]
 [219 117  31]
 [192  76  27]
 [182  78  30]
 [213 117  25]
 [213 108  31]
 [195  94  31]
 [216 146  23]
 [219 117  25]
 [216 112  25]
 [213 120  27]
 [216 117  31]
 [213 108  30]
 [186 119  27]
 [185  81  26]
 [179  83  23]
 [195  94  24]
 [213 108  25]
 [192  85  21]
 [222 125  31]
 [185  96  30]
 [231 139  26]
 [213 114  22]
 [182  76  24]
 [188  83  29]
 [179  83  28]
 [219 117  29]
 [179  83  30]
 [213 114  24]
 [195  94  23]
 [185  76  26]
 [195  94  27]
 [185  76  24]
 [213 108  25]
 [195  94  30]
 [186 125  22]
 [195  94  25]
 [195  94  32]
 [185  81  35]
 [216 146  28]
 [186 121  25]
 [185  81  23]
 [185 108  23]
 [213 120  27]
 [185 108  22]
 [216 146  24]
 [216 112  37]
 [192  90  26]
 [210 117  20]
 [185 108  23]
 [210 114  28]
 [216 112  29]
 [182  78  30]
 [216 112  23]
 [216 146  25]
 

In [3]:
#the number of samples in the training set
training_m, test_m = 195, 65
m_training = training_m 

#the number of samples in the test set
m_test = test_m 

X_training = X[:195]   #instances for the training set
Y_training = Y[:195]   #labels for the training set


X_test = X[195:]   #instances for test set
Y_test = Y[195:]   #labels for the test set

print(X_training)
print(Y_training)
print(m_test)

print("Shape of training set: " + str(X_training.shape))
print("Shape of test set: " + str(X_test.shape))

[[182  78  29]
 [213 108  24]
 [186 108  22]
 [185  76  24]
 [213 119  23]
 [182  78  28]
 [188  87  24]
 [216 114  30]
 [210 114  24]
 [192  90  21]
 [219 117  31]
 [192  76  27]
 [182  78  30]
 [213 117  25]
 [213 108  31]
 [195  94  31]
 [216 146  23]
 [219 117  25]
 [216 112  25]
 [213 120  27]
 [216 117  31]
 [213 108  30]
 [186 119  27]
 [185  81  26]
 [179  83  23]
 [195  94  24]
 [213 108  25]
 [192  85  21]
 [222 125  31]
 [185  96  30]
 [231 139  26]
 [213 114  22]
 [182  76  24]
 [188  83  29]
 [179  83  28]
 [219 117  29]
 [179  83  30]
 [213 114  24]
 [195  94  23]
 [185  76  26]
 [195  94  27]
 [185  76  24]
 [213 108  25]
 [195  94  30]
 [186 125  22]
 [195  94  25]
 [195  94  32]
 [185  81  35]
 [216 146  28]
 [186 121  25]
 [185  81  23]
 [185 108  23]
 [213 120  27]
 [185 108  22]
 [216 146  24]
 [216 112  37]
 [192  90  26]
 [210 117  20]
 [185 108  23]
 [210 114  28]
 [216 112  29]
 [182  78  30]
 [216 112  23]
 [216 146  25]
 [186 119  26]
 [213 108  30]
 [192  90 

In [7]:
#add an 1 to each sample
arr_x1 = np.ones((195, 1))
Xh = np.hstack((X_training, arr_x1))
print(Xh)

arr_y1 = np.ones((65, ))
Yh = np.hstack((Y_training, arr_y1))
print(Yh)
print(len(Xh))

[[182.  78.  29.   1.]
 [213. 108.  24.   1.]
 [186. 108.  22.   1.]
 [185.  76.  24.   1.]
 [213. 119.  23.   1.]
 [182.  78.  28.   1.]
 [188.  87.  24.   1.]
 [216. 114.  30.   1.]
 [210. 114.  24.   1.]
 [192.  90.  21.   1.]
 [219. 117.  31.   1.]
 [192.  76.  27.   1.]
 [182.  78.  30.   1.]
 [213. 117.  25.   1.]
 [213. 108.  31.   1.]
 [195.  94.  31.   1.]
 [216. 146.  23.   1.]
 [219. 117.  25.   1.]
 [216. 112.  25.   1.]
 [213. 120.  27.   1.]
 [216. 117.  31.   1.]
 [213. 108.  30.   1.]
 [186. 119.  27.   1.]
 [185.  81.  26.   1.]
 [179.  83.  23.   1.]
 [195.  94.  24.   1.]
 [213. 108.  25.   1.]
 [192.  85.  21.   1.]
 [222. 125.  31.   1.]
 [185.  96.  30.   1.]
 [231. 139.  26.   1.]
 [213. 114.  22.   1.]
 [182.  76.  24.   1.]
 [188.  83.  29.   1.]
 [179.  83.  28.   1.]
 [219. 117.  29.   1.]
 [179.  83.  30.   1.]
 [213. 114.  24.   1.]
 [195.  94.  23.   1.]
 [185.  76.  26.   1.]
 [195.  94.  27.   1.]
 [185.  76.  24.   1.]
 [213. 108.  25.   1.]
 [195.  94.

In [4]:
def perceptron_update(current_w, x, y):
    new_w = current_w + y*x
    return new_w

def perceptron(X, Y, max_num_iterations):
    curr_w = np.zeros(X.shape[1])
    best_w = curr_w
    num_samples = X.shape[0]
    best_error = num_samples+1
    index_missclassified = -1
    num_missclassified = 0
    for i in range(num_samples):
        permutation = np.random.permutation(num_samples)
        x = X[permutation[i],:]
        y = Y[permutation[i]]
        prediction = np.sign(np.dot(curr_w,x))
        if (prediction != y):
            index_missclassified = permutation[i]
            num_missclassified += 1
    if num_missclassified < best_error:
        best_error = num_missclassified
        best_w = curr_w
    num_iter = 1
    while ((index_missclassified != -1) and (num_iter < max_num_iterations)):
        curr_w = perceptron_update(curr_w, X[index_missclassified,:],Y[index_missclassified])
        index_missclassified = -1
        num_missclassified = 0
        for i in range(num_samples):
            permutation = np.random.permutation(num_samples)
            x = X[permutation[i],:]
            y = Y[permutation[i]]
            prediction = np.sign(np.dot(curr_w,x))
            if (prediction != y):
                index_missclassified = permutation[i]
                num_missclassified += 1
        if num_missclassified < best_error:
            best_error = num_missclassified
            best_w = curr_w
        num_iter += 1
    best_error = float(best_error)/float(num_samples)
    return best_w, best_error

In [5]:
#the perceptron for 100 iterations
w_found, error = perceptron(X_training,Y_training, 100)
print("Training Error of perpceptron (100 iterations): " + str(error))

#predictions on test dataset
num_errors = 0.

for i in range(m_test):
    x = X_test[i,:]
    y = Y_test[i]
    predicted = np.sign(np.dot(w_found,x))
    if (predicted != y):
        num_errors += 1


true_loss_estimate = num_errors/m_test  # error rate on the test set
print("Test Error of perpceptron (100 iterations): " + str(true_loss_estimate))

Training Error of perpceptron (100 iterations): 0.09743589743589744
Test Error of perpceptron (100 iterations): 0.13846153846153847


In [6]:
#the perceptron for 5000 iterations
w_found, error = perceptron(X_training,Y_training, 5000)
print("Training Error of perpceptron (5000 iterations): " + str(error))

num_errors = 0.

for i in range(m_test):
    x = X_test[i,:]
    y = Y_test[i]
    predicted = np.sign(np.dot(w_found,x))
    if (predicted != y):
        num_errors += 1


true_loss_estimate = num_errors/m_test  # error rate on the test set

print("Test Error of perpceptron (5000 iterations): " + str(true_loss_estimate))

Training Error of perpceptron (5000 iterations): 0.015384615384615385
Test Error of perpceptron (5000 iterations): 0.13846153846153847
